[package]
name = "woohoo"
version = "0.1.0"
authors = ["Luca Bracone <lucabr123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sysinfo = {version = "*", default-features = true}